server {
    listen 80;
    server_name it-skill-dev.ru;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name it-skill-dev.ru;

    ssl_certificate /etc/letsencrypt/live/it-skill-dev.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/it-skill-dev.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /opt/apps/skill-dev-platform/frontend/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
